### ISSUE TITLE
Enhancement to allow incremental as a list

### ISSUE THREAD

**Issue by swarwick** [epam/java-cme-mdp3-handler#33]
Currently each incremental message is broken out into individual call backs per NO_MD_ENTRIES or NO_ORDER_ID_ENTRIES but sometimes its preferable to let the end user deal with the entire messages as a whole and deal with the entries.
I would recommend an option to allow the message be output per entry or per message on the callback., preferably by adding a new callback which would be used if the option was enabled as to not break any existing code.

**Comment by iamolever** [comment]
The issue is that incremental refresh callback is result of state machine resolution, where input event is one entry with RPTSEQNUM(83) of the instrument. It's still possible to design optional flow (and redesign sequence of calls of involved objects), but I worry about cases with many instruments in one message. I will think...

**Comment by swarwick** [comment]
This can be resolved with Issue #48 so the resulting system can deal with it however they want so closing this issue in favor of that being accepted.
